{alpha: 0.4, blip_model_visual_tokenization: ckpt/finetuned/model_base_retrieval_coco.pth,
caption: true, caption_model_ckpt: /mnt/default/ruox/Projects/MultiModalKnowledge/chkpt/finetuned/model_base_caption_capfilt_large.pth,
clip_model_visual_tokenization: openai/clip-vit-large-patch14, do_sentence_tokenization: true,
early_stop_step: -1, end_time: null, filter: true, filter_generated_only: true, filter_mode: max_filter,
filterer_model_ckpt: /mnt/default/ruox/Projects/MultiModalKnowledge/chkpt/finetuned/model_base_retrieval_coco.pth,
fps: -1, frm_sampling_strategy: headtail, generation_mode: beam, height: null, image_size: 384,
k_test: 128, keep_original_caption: false, negative_all_rank: true, num_frm_CapFilt: 4,
num_frm_train: 8, num_frm_visual_tokenization: 8, ontology: vg, prompt_version_visual_tokenization: v1,
queue_size: 57600, save_frame_dir: visual_token_generation/frames/msrvtt, save_frames: false,
start_time: null, threshold: 0.4, topk_visualize: 5, train_ann_jsons: /mnt/data/VL/MSRVTT_caption/ann/video_2_text_original_full.json,
video_formats: mp4, video_roots: /mnt/data/VL/MSRVTT_ret/videos, vit: base, vit_ckpt_layer: 4,
vit_grad_ckpt: true, width: null}
